"""
A module containing LUTs for irreducible polynomials.
"""

from .irreducible_polys_2 import (
    IRREDUCIBLE_POLYS_2_1,
    IRREDUCIBLE_POLYS_2_2,
    IRREDUCIBLE_POLYS_2_3,
    IRREDUCIBLE_POLYS_2_4,
    IRREDUCIBLE_POLYS_2_5,
    IRREDUCIBLE_POLYS_2_6,
    IRREDUCIBLE_POLYS_2_7,
    IRREDUCIBLE_POLYS_2_8,
)
from .irreducible_polys_3 import (
    IRREDUCIBLE_POLYS_3_1,
    IRREDUCIBLE_POLYS_3_2,
    IRREDUCIBLE_POLYS_3_3,
    IRREDUCIBLE_POLYS_3_4,
    IRREDUCIBLE_POLYS_3_5,
    IRREDUCIBLE_POLYS_3_6,
)
from .irreducible_polys_4 import (
    IRREDUCIBLE_POLYS_4_1,
    IRREDUCIBLE_POLYS_4_2,
    IRREDUCIBLE_POLYS_4_3,
)
from .irreducible_polys_5 import (
    IRREDUCIBLE_POLYS_5_1,
    IRREDUCIBLE_POLYS_5_2,
    IRREDUCIBLE_POLYS_5_3,
    IRREDUCIBLE_POLYS_5_4,
)
from .irreducible_polys_9 import (
    IRREDUCIBLE_POLYS_9_1,
    IRREDUCIBLE_POLYS_9_2,
    IRREDUCIBLE_POLYS_9_3,
)
from .irreducible_polys_25 import IRREDUCIBLE_POLYS_25_1, IRREDUCIBLE_POLYS_25_2

IRREDUCIBLE_POLYS = [
    (2, 1, IRREDUCIBLE_POLYS_2_1),
    (2, 2, IRREDUCIBLE_POLYS_2_2),
    (2, 3, IRREDUCIBLE_POLYS_2_3),
    (2, 4, IRREDUCIBLE_POLYS_2_4),
    (2, 5, IRREDUCIBLE_POLYS_2_5),
    (2, 6, IRREDUCIBLE_POLYS_2_6),
    (2, 7, IRREDUCIBLE_POLYS_2_7),
    (2, 8, IRREDUCIBLE_POLYS_2_8),
    (2**2, 1, IRREDUCIBLE_POLYS_4_1),
    (2**2, 2, IRREDUCIBLE_POLYS_4_2),
    (2**2, 3, IRREDUCIBLE_POLYS_4_3),
    (3, 1, IRREDUCIBLE_POLYS_3_1),
    (3, 2, IRREDUCIBLE_POLYS_3_2),
    (3, 3, IRREDUCIBLE_POLYS_3_3),
    (3, 4, IRREDUCIBLE_POLYS_3_4),
    (3, 5, IRREDUCIBLE_POLYS_3_5),
    (3, 6, IRREDUCIBLE_POLYS_3_6),
    (3**2, 1, IRREDUCIBLE_POLYS_9_1),
    (3**2, 2, IRREDUCIBLE_POLYS_9_2),
    (3**2, 3, IRREDUCIBLE_POLYS_9_3),
    (5, 1, IRREDUCIBLE_POLYS_5_1),
    (5, 2, IRREDUCIBLE_POLYS_5_2),
    (5, 3, IRREDUCIBLE_POLYS_5_3),
    (5, 4, IRREDUCIBLE_POLYS_5_4),
    (5**2, 1, IRREDUCIBLE_POLYS_25_1),
    (5**2, 2, IRREDUCIBLE_POLYS_25_2),
]
